kumuluzee:
  datasources:
    - jndi-name: jdbc/PrekrskiDS
      connection-url: jdbc:postgresql://localhost:5432/prekrski
      username: postgres
      password: postgres
      pool:
        max-size: 20
  persistence-units:
    - name: "kumuluzee-samples-jpa"
      continue-on-error: false