kumuluzee:
  name: prekrski
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://0.0.0.0:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/PrekrskiDS
      connection-url: jdbc:postgresql://34.122.241.182:5432/prekrski
      username: postgres
      password: X2CY4dBkNa1i
      pool:
        max-size: 20
  persistence-units:
    - name: "evinjete-prekrski"
      continue-on-error: false
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    consul:
      agent: http://hashicorp-consul-server.default.svc.cluster.local:8500
  discovery:
    ttl: 20
    ping-interval: 15
    consul:
      agent: http://hashicorp-consul-server.default.svc.cluster.local:8500

slike-config:
  slike-age-property: 3